site_url: https://sharp-hamilton-5f5cdc.netlify.app/
logo_url: https://sharp-hamilton-5f5cdc.netlify.app/fairwind-icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          - { label: Site Email, name: siteemail, widget: string, required: false }
          - {
              label: Keywords,
              name: keywords,
              widget: list,
              field: { label: 'Keyword', name: 'keyword', widget: 'string' },
            }
          - { label: Site URL, name: siteurl, widget: string, required: false }
          - { label: 'Meta image', name: 'ogimage', widget: image, required: true, allow_multiple: false }
  - name: 'blog'
    label: 'Blog Post'
    # identifier_field: name
    folder: 'assets/content/blog'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  - name: 'sitesections'
    label: 'Site Sections'
    files:
      - label: 'Landing Hero'
        name: 'landinghero'
        file: 'assets/content/site/hero.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Video Url', name: 'videourl', widget: 'string' }
          - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
          - { label: 'Intro Text', name: 'introtext', widget: 'markdown' }
      - label: 'Our Tours'
        name: 'tours'
        file: 'assets/content/site/tours.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - label: 'Tours'
            name: 'tours'
            collapsed: false
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
              - { label: 'Length', name: 'length', widget: 'string' }
              - { label: 'Cost', name: 'cost', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Build your own'
        name: 'buildyourown'
        file: 'assets/content/site/buildyourown.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Hero image', name: 'heroimage', widget: 'image', required: true, allow_multiple: false }
          - { label: 'Side Text', name: 'sidetext', widget: 'markdown' }
          - label: 'Options List'
            name: 'optionslist'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
      - label: 'About Us'
        name: 'aboutus'
        file: 'assets/content/site/aboutus.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }
          - { label: 'Quote', name: 'quote', widget: 'markdown' }
      - label: 'Our Flagship'
        name: 'flagship'
        file: 'assets/content/site/flagship.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Video URL', name: 'videourl', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Images'
            name: 'images'
            widget: 'list'
            required: true
            summary: '{{ fields.image }}'
            fields:
              - { label: 'Image name', name: 'alt', widget: 'string' }
              - { label: 'Image', name: 'src', widget: 'image' }
      - label: 'Testimonials'
        name: 'testimonials'
        file: 'assets/content/site/testimonials.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Testimonials'
            name: 'testimonialslist'
            widget: 'list'
            fields:
              - { label: 'Customer Name', name: 'customername', widget: 'string' }
              - { label: 'Quote', name: 'quote', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image', required: true, allow_multiple: false }

      - label: 'Contact Us'
        name: 'contactus'
        file: 'assets/content/site/contactus.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Facebook', name: 'facebook', widget: 'string' }
          - { label: 'Instagram', name: 'instagram', widget: 'string' }
          - { label: 'Location', name: 'location', widget: 'map' }
      - label: 'FAQs'
        name: 'faqs'
        file: 'assets/content/site/faqs.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - label: 'Frequent Asked Questions'
            name: 'list'
            widget: 'list'
            fields:
              - { label: 'Question', name: 'question', widget: 'string' }
              - { label: 'Answer', name: 'answer', widget: 'string' }

      - label: 'Crew'
        name: 'crew'
        file: 'assets/content/site/crew.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Crew Members'
            name: 'members'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Role', name: 'role', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image', required: false, allow_multiple: false }
              - { label: 'Blurb', name: 'blurb', widget: 'markdown' }
